version = 0.1
[default.deploy.parameters]
stack_name = "streaming-music-service"
resolve_s3 = true
s3_prefix = "streaming-music-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
