AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  PlayListApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.ghostzone.playlist_service.infrastructure.AWServerless.StreamLambdaHandler::handleRequest
      Runtime: java17
      VpcConfig:
        SecurityGroupIds:
          - sg-024a04c4442e0dfcb
        SubnetIds:
          - subnet-070f0c416bfc36baf
          - subnet-02e7192b98ea29b6a
          - subnet-048ea2667ee03929f
          - subnet-0ebc9815d47e71219
          - subnet-07ac3b1ef6193e64b
          - subnet-07056469b5e621ff5
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        CREATEPLAYLIST:
          Type: Api
          Properties:
            Path: /playlist
            Method: POST
